name: transTWAS_env
channels:
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-r.utils
  - conda-forge::r-data.table
  - bioconda::r-wgcna
  - conda-forge::r-optparse
  - conda-forge::r-rcppeigen
  - conda-forge/label/cf201901::glmnet
  - conda-forge::r-glmnet
  - conda-forge::r-matrixeqtl
  - conda-forge::r-devtools
  - conda-forge::r-tidyr
  - conda-forge::r-mclust
prefix: /home/kbrunton/.conda/envs/transTWAS_env
